# See https://github.com/silverstripe/silverstripe-travis-support for setup details

language: php

dist: precise

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=MYSQL CORE_RELEASE=3.5

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3 COVERAGE="--coverage-clover=coverage.xml"

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/build/ss
  - cd ~/build/ss

script:
  - vendor/bin/phpunit "$COVERAGE" debugbar/tests

after_success:
  - >
    test "$COVERAGE" != ""
    && mv coverage.xml ~/build/$TRAVIS_REPO_SLUG
    && cd ~/build/$TRAVIS_REPO_SLUG
    && bash <(curl -s https://codecov.io/bash)
